### ISSUE TITLE
Modal UI > Store relation data

### ISSUE THREAD

**Issue by mfendeksilverstripe** [maxime-rainville/silverstripe-anyfield#31]
# Modal UI > Store relation data

Looks like the update of relation data isn't working at all. The UI indicates everything is fine but I don't see DB record being updated after the save action on both modal UI and then the parent record (content block).

![Screenshot 2023-12-13 at 9 58 27 AM](https://github.com/maxime-rainville/silverstripe-anyfield/assets/26395487/7ca3cdab-2e97-41bd-986b-0dbc4b9a75e8)

![Screenshot 2023-12-13 at 9 58 40 AM](https://github.com/maxime-rainville/silverstripe-anyfield/assets/26395487/04ccdcc9-6e01-44da-8642-52c439d250f2)

## Steps to reproduce

* edit an item
* attach an image
* save via modal UI
* save content block
* reload the page
* image is gone

**Comment by maxime-rainville** [comment]
Duplicate of https://github.com/maxime-rainville/silverstripe-anyfield/issues/32.

That's a known limitation. I don't know how hard or easy it would be to fix. We did manage to get it working on LinkField.

I think part of the issue is that the FormSchema component doesn't like having nested forms in them. To get that working we might need to fix it in core.

**Comment by mfendeksilverstripe** [comment]
Attempted fix https://github.com/maxime-rainville/silverstripe-anyfield/pull/35

**Comment by mfendeksilverstripe** [comment]
Related PR merged
